/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.ip;

import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author i14505i
 */
public class Form_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Form_Principal
     */
    public Form_Principal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_1 = new javax.swing.JSpinner();
        txt_2 = new javax.swing.JSpinner();
        txt_3 = new javax.swing.JSpinner();
        txt_4 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_executar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_rede = new javax.swing.JTextField();
        txt_maquina = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_classe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_1.setModel(new javax.swing.SpinnerNumberModel());
        txt_1.setToolTipText("");

        txt_2.setModel(new javax.swing.SpinnerNumberModel());
        txt_2.setToolTipText("\"Número de 0 a 255\"");

        txt_3.setModel(new javax.swing.SpinnerNumberModel());

        txt_4.setModel(new javax.swing.SpinnerNumberModel());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(".");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(".");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(".");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btn_executar.setText("> > >");
        btn_executar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_executarActionPerformed(evt);
            }
        });

        jLabel4.setText("Rede:");

        jLabel5.setText("Máquina:");

        txt_classe.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txt_classe.setText("<<Classe>>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(btn_executar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_maquina, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_rede, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(txt_classe)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txt_4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(341, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(btn_executar)
                .addGap(18, 18, 18)
                .addComponent(txt_classe)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_rede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_maquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_executarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_executarActionPerformed

        int Ip_parte1 = Integer.parseInt(txt_1.getValue().toString());

        int Ip_parte2 = Integer.parseInt(txt_2.getValue().toString());

        int Ip_parte3 = Integer.parseInt(txt_3.getValue().toString());

        int Ip_parte4 = Integer.parseInt(txt_4.getValue().toString());

        if (Ip_parte1 <= 126) {
            //CLASSE A
            txt_classe.setText("Classe A");
            
            txt_rede.setText("" + Ip_parte1);
            
            txt_maquina.setText("" + Ip_parte2 + "." + Ip_parte3 + "." + Ip_parte4);
            

        } else if ((Ip_parte1 <= 191) && (Ip_parte1 >= 128)) {
            //CLASSE B
            txt_classe.setText("Classe B");
            
            txt_rede.setText("" + Ip_parte1 + "." + Ip_parte2);
            
            txt_maquina.setText("" + Ip_parte3 + "." + Ip_parte4);
            
            
        } else if ((Ip_parte1 <= 223) && (Ip_parte1 >= 192)) {
            //CLASSE C
            txt_classe.setText("Classe C");
            
            txt_rede.setText("" + Ip_parte1 + "." + Ip_parte2  + "." + Ip_parte3);
            
            txt_maquina.setText("" + Ip_parte4);
            
            
        } else if ((Ip_parte1 <= 239) && (Ip_parte1 >= 224)) {
            
            txt_classe.setText("Classe D");
            
            txt_maquina.setText("");
            txt_maquina.setEnabled(false);
            
            txt_rede.setText("");
            txt_rede.setEnabled(false);
            
        }else if ((Ip_parte1 <= 255) && (Ip_parte1 >= 240)) {
            
            txt_classe.setText("Classe E");
            
            txt_maquina.setText("");
            txt_maquina.setEnabled(false);
            
            txt_rede.setText("");
            txt_rede.setEnabled(false);
            
        }

        
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter(".\\LOG.txt", true));
            bw.write(txt_1.getValue() + "." + txt_2.getValue() + "." + txt_3.getValue() + "." + txt_4.getValue() + "." +";");

            bw.newLine();
            bw.flush();
            bw.close();
            JOptionPane.showMessageDialog(null, "Novo cliente cadastrado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Falha no cadastro");
        }
        
        
        
    }//GEN-LAST:event_btn_executarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_executar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner txt_1;
    private javax.swing.JSpinner txt_2;
    private javax.swing.JSpinner txt_3;
    private javax.swing.JSpinner txt_4;
    private javax.swing.JLabel txt_classe;
    private javax.swing.JTextField txt_maquina;
    private javax.swing.JTextField txt_rede;
    // End of variables declaration//GEN-END:variables
}
