/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.cadastro;

/**
 *
 * @author i14505i
 */
public class frm_menu extends javax.swing.JFrame {

    /**
     * Creates new form frm_menu
     */
    public frm_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bar_menu = new javax.swing.JMenuBar();
        menu_cadastro = new javax.swing.JMenu();
        cadastro_cliente = new javax.swing.JMenuItem();
        cadastro_livro = new javax.swing.JMenuItem();
        cadastro_reserva = new javax.swing.JMenuItem();
        f2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu_cadastro.setText("Cadastro");

        cadastro_cliente.setText("Cliente");
        cadastro_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastro_clienteActionPerformed(evt);
            }
        });
        menu_cadastro.add(cadastro_cliente);

        cadastro_livro.setText("Livro");
        cadastro_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastro_livroActionPerformed(evt);
            }
        });
        menu_cadastro.add(cadastro_livro);

        cadastro_reserva.setText("Reserva");
        cadastro_reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastro_reservaActionPerformed(evt);
            }
        });
        menu_cadastro.add(cadastro_reserva);

        bar_menu.add(menu_cadastro);

        f2.setText("F2");
        bar_menu.add(f2);

        setJMenuBar(bar_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastro_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastro_clienteActionPerformed
        // TODO add your handling code here:
        frm_cliente cliente = new frm_cliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_cadastro_clienteActionPerformed

    private void cadastro_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastro_livroActionPerformed
        // TODO add your handling code here:
        frm_livro livro = new frm_livro();
        livro.setVisible(true);
    }//GEN-LAST:event_cadastro_livroActionPerformed

    private void cadastro_reservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastro_reservaActionPerformed
        // TODO add your handling code here:
        frm_reserva reserva = new frm_reserva();
        reserva.setVisible(true);
    }//GEN-LAST:event_cadastro_reservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar bar_menu;
    private javax.swing.JMenuItem cadastro_cliente;
    private javax.swing.JMenuItem cadastro_livro;
    private javax.swing.JMenuItem cadastro_reserva;
    private javax.swing.JMenu f2;
    private javax.swing.JMenu menu_cadastro;
    // End of variables declaration//GEN-END:variables
}
