/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.launchpad;

import javax.swing.ImageIcon;

/**
 *
 * @author i14615i
 */
public class frm_launchpad extends javax.swing.JFrame {

    /**
     * Creates new form frm_launchpad
     */
    public frm_launchpad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tecla3 = new javax.swing.JLabel();
        tecla1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Launchpad Virtual :)");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        tecla3.setAlignmentY(0.0F);
        tecla3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tecla3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tecla3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tecla3MouseReleased(evt);
            }
        });
        getContentPane().add(tecla3);
        tecla3.setBounds(90, 90, 48, 48);

        tecla1.setAlignmentY(0.0F);
        tecla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tecla1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tecla1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tecla1MouseReleased(evt);
            }
        });
        getContentPane().add(tecla1);
        tecla1.setBounds(34, 92, 48, 48);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/launchpad.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 601, 606);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tecla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tecla1MouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_tecla1MouseClicked

    private void tecla1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tecla1MousePressed
        // TODO add your handling code here:
        tecla1.setIcon(new ImageIcon("E:\\1 - Técnico\\02 - PC - Programação de Computadores\\14 - Projeto(Launchpad)\\Projeto(Launchpad)\\src\\imagens\\tecla.jpg"));
    }//GEN-LAST:event_tecla1MousePressed

    private void tecla1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tecla1MouseReleased
        // TODO add your handling code here:
        tecla1.setIcon(null);
    }//GEN-LAST:event_tecla1MouseReleased

    private void tecla3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tecla3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tecla3MouseClicked

    private void tecla3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tecla3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tecla3MousePressed

    private void tecla3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tecla3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tecla3MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_launchpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_launchpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_launchpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_launchpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_launchpad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel tecla1;
    private javax.swing.JLabel tecla3;
    // End of variables declaration//GEN-END:variables
}
