/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.rotedores;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author i14505i
 */
public class formulario_principal extends javax.swing.JFrame {

    /**
     * Creates new form formulario_principal
     */
    public formulario_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_opcoes = new javax.swing.ButtonGroup();
        rb_marca = new javax.swing.JRadioButton();
        rb_velocidade = new javax.swing.JRadioButton();
        opcao_numero_antenas = new javax.swing.JRadioButton();
        txt_pesquisa = new javax.swing.JTextField();
        btn_pesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        grupo_opcoes.add(rb_marca);
        rb_marca.setText("Marca");

        grupo_opcoes.add(rb_velocidade);
        rb_velocidade.setText("Velocidade");

        grupo_opcoes.add(opcao_numero_antenas);
        opcao_numero_antenas.setText("Número antenas");

        txt_pesquisa.setText("Multilaser");

        btn_pesquisar.setText("Pesquisar");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });

        jLabel1.setText("Digite");

        jtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(rb_marca)
                        .addGap(28, 28, 28)
                        .addComponent(rb_velocidade)
                        .addGap(18, 18, 18)
                        .addComponent(opcao_numero_antenas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_pesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_marca)
                    .addComponent(rb_velocidade)
                    .addComponent(opcao_numero_antenas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pesquisar)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
        try {
            // 1. CARREGAR O DRIVER
            Class.forName("com.mysql.jdbc.Driver");
            
            //2. CRIAR A CONEXAO
            Connection conexao = DriverManager.getConnection("jdbc:mysql://localhost/projeto_roteadores", "root", "");
            //3. PREPARAR O COMANDO SQL
            PreparedStatement comando = null;
            
            // 4. DE ACORDO COM A OPÇÃO DESEJADA IRÁ CRIAR UM SQL
            if (rb_marca.isSelected()) {
                comando = conexao.prepareStatement("SELECT * FROM ROTEADORES WHERE MARCA = ?");
            }
            if (rb_velocidade.isSelected()) {
                comando = conexao.prepareStatement("SELECT * FROM ROTEADORES WHERE VELOCIDADE = ?");
            }
            //5. ADICIONANDO O PARAMETRO DA CONSULTA
            comando.setString(1, txt_pesquisa.getText());

            //6. EXECUTANDO A CONSULTA
            ResultSet resultado_consulta = comando.executeQuery();
            //7. CRIAR UM MODELO DE GRADE COM AS COLUNAS DEFINIDAS
            DefaultTableModel modelo = new DefaultTableModel(null, new String[]{
                "CODREF", "MARCA", "MODELO", "VELOCIDADE", "ANTENAS", "PREÇO"});

            //8. VARIAVEL DE DADOS 
            String[] linha = new String[6];

            // 9. PARA CADA RESULTADO PREENCHA UMA LINHA DE DADOS
            while (resultado_consulta.next()) {

                linha[0] = resultado_consulta.getString("CODREF"); //onde "ID" é o nome da coluna no seu banco de dados
                linha[1] = resultado_consulta.getString("MARCA");
                linha[2] = resultado_consulta.getString("MODELO");
                linha[3] = resultado_consulta.getString("VELOCIDADE");
                linha[4] = resultado_consulta.getString("ANTENAS");
                linha[5] = resultado_consulta.getString("PRECO");
                // 10. ADICIONA UMA NOVA LINHA DE DADOS NA GRADE
                modelo.addRow(linha); //adiciona uma nova linha em sua JTable;
            }

            // 11. ASSOCIA O MODELO DE DADOS A GRADE
            jtable1.setModel(modelo);

            //12. FECHA A CONEXAO
            conexao.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro na consulta");
        }
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.ButtonGroup grupo_opcoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtable1;
    private javax.swing.JRadioButton opcao_numero_antenas;
    private javax.swing.JRadioButton rb_marca;
    private javax.swing.JRadioButton rb_velocidade;
    private javax.swing.JTextField txt_pesquisa;
    // End of variables declaration//GEN-END:variables
}
