//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Piano_.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projeto_Piano_.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream dearGod {
            get {
                return ResourceManager.GetStream("dearGod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00:01 panel1
        ///00:03 panel15
        ///00:05 panel4
        ///00:07 panel2
        ///00:09 panel7
        ///00:11 panel1
        ///00:13 panel2
        ///00:16 panel4
        ///00:18 panel18
        ///00:20 panel1
        ///00:22 panel4
        ///00:25 panel2
        ///00:29 panel55
        ///00:33 panel41
        ///00:36 panel33
        ///00:39 panel1
        ///00:40 panel15
        ///00:42 panel4
        ///00:44 panel2
        ///00:46 panel7
        ///00:47 panel1
        ///00:48 panel2
        ///00:51 panel1
        ///00:54 panel15
        ///00:58 panel4
        ///01:01 panel54
        ///01:02 panel10
        ///01:05 panel22
        ///01:10 panel44
        ///01:14 panel1
        ///01:17 panel33
        ///01:22 panel21
        ///01:24 panel64
        ///01:25 panel13
        ///01:28 panel12
        ///01:30  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mapa1 {
            get {
                return ResourceManager.GetString("mapa1", resourceCulture);
            }
        }
    }
}
