CREATE DATABASE PROJETO_ROTEADORES;
USE PROJETO_ROTEADORES;
CREATE TABLE ROTEADORES (
	CODREF INT PRIMARY KEY,
	MARCA VARCHAR (100),
	MODELO VARCHAR(100),
	VELOCIADE VARCHAR(100),
	ANTENAS VARCHAR(10),
	PRECO VARCHAR(10)
);